name: Deploy Alternative (Manual)

on:
  workflow_dispatch:
    inputs:
      deploy_method:
        description: 'Способ деплоя'
        required: true
        default: 'ftp'
        type: choice
        options:
        - ftp
        - rsync
        - manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Prepare files
      run: |
        echo "📦 Подготовка файлов для деплоя..."
        cd ./dist
        
        # Создаем архив для ручной загрузки
        tar -czf ../../manual-deploy.tar.gz .
        
        echo "✅ Архив создан: manual-deploy.tar.gz"
        echo "📋 Размер архива:"
        ls -lh ../../manual-deploy.tar.gz
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deploy-files
        path: manual-deploy.tar.gz
        
    - name: Deploy via FTP (if selected)
      if: ${{ github.event.inputs.deploy_method == 'ftp' }}
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ secrets.FTP_PATH }}
        dangerous-clean-slate: false
        dry-run: false
        log-level: verbose
        
    - name: Deploy via rsync (if selected)
      if: ${{ github.event.inputs.deploy_method == 'rsync' }}
      run: |
        echo "🚀 Деплой через rsync..."
        # Добавьте команды rsync здесь
        
    - name: Manual deploy instructions
      if: ${{ github.event.inputs.deploy_method == 'manual' }}
      run: |
        echo "📋 Инструкции для ручного деплоя:"
        echo "1. Скачайте архив manual-deploy.tar.gz из артефактов"
        echo "2. Распакуйте архив на сервере"
        echo "3. Загрузите файлы в корневую папку сайта"
        echo "4. Настройте права доступа: chmod 755 для папок, 644 для файлов"
        echo "5. Запустите setup-webhook.php для настройки бота"
